### ISSUE TITLE
Clipboard on insecure pages

### ISSUE THREAD

**Issue by ghoofman** [alDuncanson/Copycat#11]
**Describe the bug**
Unable to copy text in the clipboard in http (non-secure) web pages.

**To Reproduce**
1. Visit an http site 
2. Try to copy text
3. It'll produce an exception trying to read clipboard from navigator

**Expected behavior**
It should get the text from the clipboard

**Additional context**
Likely not a thing that can be overcome without a Chrome flag, since it seems to be a Chrome security thing.

**Comment by alDuncanson** [comment]
Yep, looks like this is a chrome security feature:

> As with many new APIs, the Clipboard API is only supported for pages served over HTTPS.

More can be read here: https://web.dev/async-clipboard/#security-and-permissions
